---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "logstash.fullname" . }}-pipelines
  labels:
    app: {{ template "logstash.name" . }}
    chart: {{ template "logstash.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  {{- range $id, $content := .Values.pipelines }}
  {{ $id }}.pipeline: |
    {{- $content | nindent 4 }}
  {{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "logstash.fullname" . }}-pipeline-settings
  labels:
    app: {{ template "logstash.name" . }}
    chart: {{ template "logstash.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  pipelines.yml: |-
  {{- range $id, $_ := .Values.pipelines }}
    - pipeline.id: {{ $id }}
      path.config: "{{ $.Values.pipelinesPath }}/{{ $id }}.pipeline"
      {{- $settings := index $.Values.pipelineSettings $id }}
      {{- range $key, $val:= $settings }}
      {{ $key }}: {{ $val }}
      {{- end }}
  {{- end }}
