apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "logstash.fullname" . }}-pipelines
  labels:
    app: {{ template "logstash.name" . }}
    chart: {{ template "logstash.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  {{- range $id, $content := .Values.pipelines }}
  {{ $id }}.pipeline: |
    {{- $content | nindent 4 }}
  {{- end }}
